// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('AdminLogin', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('AdminLogin', async function() {
    await driver.get("https://stsweng-eight.vercel.app/")
    await driver.manage().window().maximize()
    await driver.wait(until.elementLocated(By.id("username")), 10000);
    await driver.findElement(By.id("username")).click()
    await driver.sleep(500)
    await driver.findElement(By.id("username")).sendKeys("Devon")

    await driver.wait(until.elementLocated(By.id("password")), 10000);
    await driver.findElement(By.id("password")).click()
    await driver.sleep(500)
    await driver.findElement(By.id("password")).sendKeys("javier")
    await driver.findElement(By.css(".py-3")).click()
  })
})
