// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CheckStatusInvalid', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CheckStatusInvalid', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.sleep(2000)
    await driver.findElement(By.linkText("Check Status")).click()
    await driver.sleep(2000)
    await driver.findElement(By.css(".text-center")).click()
    await driver.sleep(2000)
    await driver.findElement(By.css(".text-center")).sendKeys("10028")
    await driver.sleep(2000)
    await driver.findElement(By.css(".rounded-3xl")).click()
    await driver.sleep(2000)
    await driver.findElement(By.css(".lg\\3Aw\\=\\[480px\\]")).click()
    await driver.sleep(2000)
    await driver.findElement(By.css(".lg\\3Aw\\=\\[480px\\]")).sendKeys("1234")
    await driver.findElement(By.css(".bg-cusBlue:nth-child(8)")).click()
    await driver.sleep(2000)
    assert(await driver.switchTo().alert().getText() == "Incorrect password. Please try again.")
    await driver.sleep(2000)
  }) 
})
