// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ClientNavigation', function() {
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ClientNavigation', async function() {
    await driver.get("https://stsweng-eight.vercel.app/")
    await driver.manage().window().maximize()
    await driver.sleep(2000)
    await driver.executeScript("window.scrollTo(0,2300)") //scroll down
    await driver.sleep(2000)
    await driver.findElement(By.css(".right-0")).click() //moving reviews right
    await driver.sleep(1000)
    await driver.findElement(By.css(".right-0")).click()
    await driver.sleep(1000)
    await driver.findElement(By.css(".right-0")).click()
    await driver.sleep(3000)
    await driver.findElement(By.css(".top-1\\/2:nth-child(1)")).click() //moving reviews left
    await driver.sleep(1000)
    await driver.findElement(By.css(".top-1\\/2:nth-child(1)")).click()
    await driver.sleep(1000)
    await driver.findElement(By.css(".top-1\\/2:nth-child(1)")).click()
    await driver.sleep(2000)
    await driver.executeScript("window.scrollTo(0,0)") //go back to the top of the page
    await driver.sleep(2000)
    await driver.findElement(By.linkText("Services")).click()
    await driver.sleep(5000)
    await driver.findElement(By.linkText("About"));
    await driver.sleep(2000)
    await driver.findElement(By.linkText("FAQs")).click()
    await driver.sleep(5000)
    await driver.findElement(By.css(".w-full:nth-child(1) > .btn > span:nth-child(1)")).click() //Test FAQ 1
    await driver.sleep(2000)
    await driver.findElement(By.css(".w-full:nth-child(2) > .btn")).click() //Test FAQ 2
    await driver.sleep(2000)
    await driver.findElement(By.css(".w-full:nth-child(3) > .btn")).click() //Test FAQ 3
    await driver.sleep(2000)
    await driver.executeScript("window.scrollTo(0,600)") //scroll down
    await driver.sleep(2000)
    await driver.findElement(By.linkText("OR click here to send us a ticket!")).click() //Link to send in a question
    await driver.sleep(2000)
    await driver.findElement(By.linkText("Check Status")).click() 
    await driver.sleep(2000)
  })
})
