// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('EnterPersonalDetails', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('EnterPersonalDetails', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.sleep(1000)
    await driver.findElement(By.linkText("Book Now")).click()
    await driver.sleep(5000)
    await driver.findElement(By.css("a:nth-child(2) > div > .w-full")).click()
    await driver.sleep(1000)
    await driver.findElement(By.id("customerfirstname")).click()
    await driver.sleep(1000)
    await driver.findElement(By.id("customerfirstname")).sendKeys("Ren")
    await driver.sleep(1000)
    await driver.findElement(By.id("customermiddlename")).click()
    await driver.sleep(1000)
    await driver.findElement(By.id("customermiddlename")).sendKeys("Per")
    await driver.sleep(1000)
    await driver.findElement(By.id("customerlastname")).click()
    await driver.sleep(1000)
    await driver.findElement(By.id("customerlastname")).sendKeys("Dim")
    await driver.sleep(1000)
    await driver.findElement(By.css(".relative:nth-child(4) > .text-black")).click()
    await driver.sleep(1000)
    await driver.findElement(By.css(".relative:nth-child(4) > .text-black")).sendKeys("09123456789")
    await driver.sleep(1000)
    await driver.findElement(By.css(".relative:nth-child(6) > .text-black")).click()
    await driver.sleep(1000)
    await driver.findElement(By.css(".relative:nth-child(6) > .text-black")).sendKeys("dim@gmail.com")
    await driver.sleep(1000)
    await driver.findElement(By.css(".lg\\3A block")).click()
    await driver.sleep(2000)
  })
})
