name: CI + Jest

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
  schedule:
    - cron: '0 4,16 * * *' # 12AM and 12PM Philippine Time

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check code out
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Run adminLogin
      run: npx mocha adminLogin.spec.js --timeout 60000
    
    - name: Run checkStatusInvalid
      run: npx mocha checkStatusInvalid.spec.js --timeout 60000

    - name: Run checkStatusValid
      run: npx mocha checkStatusValid.spec.js --timeout 60000

    - name: Run enterPersonalDetails
      run: npx mocha enterPersonalDetails.spec.js --timeout 60000

    - name: Run clientNavigation
      run: npx mocha clientNavigation.spec.js --timeout 60000

    - name: Run adminMenuNavigation
      run: npx mocha adminMenuNavigation.spec.js --timeout 60000